0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,13 +1,28 @@
 #!/usr/bin/env bash
 
-# uploads a file to a server
+# uploads a file
+# Checking for command-line argument
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
 
-msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Assigning Arguments to variables
 
-if [ "$4" ]; then
-   scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
-elif [ "$3" ]; then
-     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "$msg";
+  echo "FILE TRANSFER FAILED"
 fi
